export const ADD_USER = 'ADD_USER'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const CREATE_NEWS = 'CREATE_NEWS'
export const SPECIFY_EDITABLE_NEWS = 'SPECIFY_EDITABLE_NEWS'
export const EDIT_NEWS = 'EDIT_NEWS'
export const DELETE_NEWS = 'DELETE_NEWS'
